### ISSUE TITLE
Blank page, console states "None of the “sha512” hashes in the integrity attribute match the content of the subresource."

### ISSUE THREAD

**Issue by jonathanrbowman** [Requarks/wiki#1091]
I had the most current beta release working great (2.0.0-beta.303), and then yesterday one of my devs decided to upgrade Postgres, which also included doing a Yum update.

The database was migrated, and the other applications on the server still work fine, but now I just get a blank white page when trying to access our wiki login.

Console in firefox states:
```
None of the “sha512” hashes in the integrity attribute match the content of the subresource.
```

Console in Chrome states:
```
...js/app.0f3831876fd85b2c39a7.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

I tried to look up some information about it possibly being a subresource integrity issue, but couldn't get very far with that. I disabled the setting in firefox that flags failing subresource integrity checks, didn't change anything. I tried redeploying the project fresh, and making sure it wasn't a Selinux issue by changing it to permissive. I didn't see anything about this in the Issues here, except something in the troubleshooting for emojis not displaying on cloudflare CDNs, but didn't see that being a solution for my issue.

Kind of out of ideas and would love some input, please!

Host Info:
OS: Centos7
Host: DigitalOcean
Server: nginx
Wiki.js version: 2.0.0-beta.303
Database engine: postgres 10
Running the process itself with PM2

**Comment by NGPixel** [comment]
Are you using Cloudflare?

**Comment by jonathanrbowman** [comment]
No Cloudflare or external CDN is being used right now, just all stored locally alongside the project on our DigitalOcean server, in a local Postgresql db.

**Comment by jonathanrbowman** [comment]
I think a better route is to try and get the Docker version of it running, so I'm going to focus on that.

Now I just have to learn Docker, and figure out how to configure nginx to hit the container correctly, and keep ssl working with it! Not sure yet if loading the config.yml or a docker-compose route is going to work better.

**Comment by NGPixel** [comment]
You have something altering the integrity of JS / CSS files between Wiki.js server and the client, which is why they get rejected by the browser.

The next build will have an option to disable the SRI security check.

**Comment by NGPixel** [comment]
You can now disable SRI in Admin > General > Security

**Comment by imbadark** [comment]
@NGPixel 
Firstly, thanks for adding a option to disable `SRI`

However, the option seems doesn't work, after set it as "disabled", the home page still alert SRI check error, and the page is blank, wonder if it was a bug or the feature is not completed? 

Thank you again for ur efforts.

_BTW, I've even tried to restart the container._

**Comment by aerlaut** [comment]
I'm having the same problem putting up Wiki.js running in a container behind Apache reverse proxy. I'm still at the setup page, so I can't disable SRI checks yet.

**Comment by NGPixel** [comment]
@aerlaut Having a reverse proxy does not modify the SRI hashes in any way unless you deliberately apply additional transforms.

**Comment by NGPixel** [comment]
@imbadark I just tested disabling SRI and the SRI hash is no longer present from script tags on subsequent page loads.

- Make sure to clear your browser cache?
- Check the page source, is there any `integrity` tags present?
- What is the exact error you're getting?

**Comment by imbadark** [comment]
> @imbadark I just tested disabling SRI and the SRI hash is no longer present from script tags on subsequent page loads.
> 
> * Make sure to clear your browser cache?
> * Check the page source, is there any `integrity` tags present?
> * What is the exact error you're getting?
Thanks for ur reply

1. I'm sure cache is disabled by F12(chrome)'s option
2. Yes, it dose exist like
```html
<script charset="utf-8" src="/js/vendor.77191088b4b58f0b0f44.js"
integrity="sha256-QbdRkUSWiOuF95wZE842+5tzKiCymZOIuQ5WULRBBUg= sha512-WgwxsB3oIqE0iRpKAfKvKCUgzw2EAtFAAD7pDnWhwa89WTcJXYeCufre4Lgc/lgFdvFJqt7//zNVlzf2GzatKw==" 
crossorigin="use-credentials">
</script>
```
3. the full error message is
> Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:7777/js/vendor.77191088b4b58f0b0f44.js' with computed SHA-256 integrity 'yxRpy+0Q+u27UYYWtZZWpfSeakaodAeflTCTgpwU6p4='. The resource has been blocked

Here's a way to reproduce it :
1. disabled the SRI option & save 
2. edit the `./assert/js/vendor.77191088b4b58f0b0f44.js` (or other js file) on docker container, add a symbol like `#` in comment line (make the file changed). then save it.
3. refresh the wiki-home page, the console will alert SRI check

Other information can be added if necessary.

**Comment by imbadark** [comment]
@NGPixel 

So any progress now? Or will it be fixed in the next version?

Look forward to ur reply, THX

**Comment by NGPixel** [comment]
Like I said, I was unable to reproduce your issue.

When you disable the SRI option, then Apply Changes, in the admin area, the "integrity" param should no longer be present in the page source. If you still see it, then you either didn't save the setting correctly or you're caching the page (a misconfigured reverse proxy, browser cache, etc.).

There's nothing for me to fix as I tested the option and it works correctly on my side.

**Comment by imbadark** [comment]
> Like I said, I was unable to reproduce your issue.
> 
> When you disable the SRI option, then Apply Changes, in the admin area, the "integrity" param should no longer be present in the page source. If you still see it, then you either didn't save the setting correctly or you're caching the page (a misconfigured reverse proxy, browser cache, etc.).
> 
> There's nothing for me to fix as I tested the option and it works correctly on my side.

I compared the diff between enable SRI & disable it, and found the problem
Here is the screenshot:
![wiki00](https://user-images.githubusercontent.com/38650392/72230801-d3cce600-35f2-11ea-8026-2938a059849c.jpg)

Seems some css & js files are not affected by the setting?

**Comment by alex-phillips** [comment]
I've found this as well. Cleared all caches, SRI setting is disabled, and still getting the error.

**Comment by Trojaner** [comment]
I am having the same issue as well, nginx reverse + cloudflare + firefox

**Comment by NGPixel** [comment]
SRI has been disabled in 7ab16e2bf3a45adbeec6c4bfcabae6e371ff71c1 until a proper solution is found to handle both SRI and non-SRI option in the same build package. It will be available in 2.1.
