### ISSUE TITLE
Default Authentication strategy on Login page

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#1214]
**Describe the bug**
"...the default Local strategy cannot be disabled as it is required for root administrator login" which results in a non-intuitive user experience at login.

Administrator should be able to select the "Primary/Default Authentication strategy".

**To Reproduce**
1. Configure new Auth strategy
2. Login page

**Expected behavior**
The username/password prompt should be replaced with, as an example, "Sign in with   [GitHub Enterprise]" as the main login item.

This decreases the user's likelihood they attempt to use another user/password to gain access, and the Local is shown only under "or login using..." because this is  always required.

**Screenshots**
![image](https://user-images.githubusercontent.com/1815807/68847103-feb7be00-06c5-11ea-9b36-c13586617648.png)

**Comment by githubdave2020** [comment]
I had to walk nearly every user through this same situation. It should be prioritized!

**Comment by signalkraft** [comment]
In my case I wanted users to always pick Keycloak and I wanted to avoid showing the regular login form altogether. Accomplished this with a simple rewrite rule from `/login` to `/login/keycloak` (in our case in Helm on Kubernetes):

```yaml
[...]
      - ingress:
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/configuration-snippet: |
              rewrite ^/login$ https://{{ requiredEnv "HOSTNAME" }}/login/keycloak redirect;
```
Works like a charm, users don't even see the login screen anymore. Obviously give your SSO user admin access first, you won't be able to use local sign in anymore.

Hope this helps somebody in the meantime.

**Comment by michidk** [comment]
Thanks, @signalkraft! Exactly what I needed. This issue should definitly be prioritized.

**Comment by steviethecat** [comment]
Agreed, this should be prioritized. This issue has kept me from upgrading to version 2 for a while now.

**Comment by NGPixel** [comment]
This is already being addressed in 2.5.

**Comment by nebulade** [comment]
> This is already being addressed in 2.5.

This is great news, as we get this confusion from our users ( Cloudron ) often as well. Is there a way to track the task for 2.5 somewhere?

**Comment by Smankusors** [comment]
> > This is already being addressed in 2.5.
> 
> This is great news, as we get this confusion from our users ( Cloudron ) often as well. Is there a way to track the task for 2.5 somewhere?

it's documented on [here](https://docs.requarks.io/releases). But it seems he missed the deadline though. 😞

**Comment by iynehz** [comment]
I was going to raise the same question but saw this ticket. If it's not really resolved should it get reopened? or shall I raise a new ticket?

**Comment by sbonaime** [comment]
@NGPixel With 2.5.314 is it possible to set a default authentication strategy ? Where can we do that ? 
Thanks

**Comment by sbonaime** [comment]
**Customize Login Flow**
It's possible to modify how the login experience is presented to the user from the Administration Area > Security section

**Bypass Login Screen**
When using a social provider (e.g. Google authentication), you may want to skip the login screen altogether and redirect the user directly to the social provider for a faster login.

You can always access the login screen even when this option is enabled by adding ?all=1 to the login URL. (e.g. https://wiki.example.com/login?all=1)

**Hide Local Provider**
If you have multiple authentication providers enabled but wish to hide the default local provider, you can enable this option to hide it.

You can always unhide it when this option is enabled by adding ?all=1 to the login URL. (e.g. https://wiki.example.com/login?all=1)
