### ISSUE TITLE
Search process indicator on empty query

### ISSUE THREAD

**Issue by UnlimitedCookies** [Requarks/wiki#1255]
**Describe the bug**
The search progress bar doesn't stop moving once text has been entered and is cleared.

**To Reproduce**
1. Go to https://docs.requarks.io/releases (or any other wiki.js installation)
2. Type some arbitrary search term (e.g. Linux) into the search box
3. Press enter (Idk if this is really necessary)
4. Clear entered text from the search box 
**Note: Clear the text all at once either by using CTRL+Backspace or by selecting the text and deleting it.**
5. Observe the "ongoing search" animation whilst the search box is empty
Also: If you now enter any search term it will always report back "No pages matching your query."

**Expected behavior**
I expect the search process to stop once the search box is emptied.
Idk if this is just the animation or if there's actually a search ongoing whilst the box is empty.

**Further suggestion for enhancing the search**
If I click with the mouse into the search box it shouldn't display "No pages matching your query."
Rather something like "Start typing to start a search" - this seems more user-friendly IMO.

Thanks!

**Comment by NGPixel** [comment]
This is regression bug, it used to show a more friendly message when empty.

**Comment by NGPixel** [comment]
Fixed by 9e35126fc5bf7255e4bda194322a96d608721b65

**Comment by UnlimitedCookies** [comment]
@NGPixel I don't think the issue has been solved.

**There are two issues still persistent that haven't been fixed.**
1. Please re-read the steps to reproduce on the issue stated above.
Once you clear the search box the search process still doesn't stop.
Watch the attached Video "1. Bug" for further clarification.
2. Once you enter a search term, clear the box with selection of the text, enter a different search term and clear the box again, if you now enter the term that has been entered first it'll show "No results".
Watch the attached Video "2. Bug" for further clarification.

Thanks!

**Comment by mendiromania** [comment]
+1 not fixed

**Comment by NGPixel** [comment]
Fixed by 144950ea7071a37b1c7e2719bcdec6accbfa7f25

**Comment by UnlimitedCookies** [comment]
Thanks for the fix!

Altough, I am not quite sure whether this fixes the second bug I pointed out or not.
So does it fix the bug to be seen in the second video that I pointed out above?

**Comment by NGPixel** [comment]
I wasn't able to reproduce your second bug in the dev version. Once 2.4 is out, open a new ticket if you still experience the bug.

**Comment by UnlimitedCookies** [comment]
Sounds wonderful! I will try it out as soon as v2.4 drops.

**Comment by pplnet** [comment]
Hi

I Installed 2.5.201 version and the bug still present.

Also happen in the documentation website:
You can try searching "sql", then clear the search box and re enter "sql".
From that moment, shows the message "No pages matching your query." every time you search the same term.

The graphql query returns the same result but the client doesn´t respond properly.

Thanks!

**Comment by slecuona** [comment]
Hi

I Installed 2.5.201 version and the bug still present.

Also happen in the documentation website:
You can try searching "sql", then clear the search box and re enter "sql".
From that moment, shows the message "No pages matching your query." every time you search the same term.

The graphql query returns the same result but the client doesn´t respond properly.

Thanks!
