### ISSUE TITLE
Git Storage Sync password and url issues

### ISSUE THREAD

**Issue by Pehesi97** [Requarks/wiki#840]
### Actual behavior
If a password has an "@" character, sync breaks.

![image](https://user-images.githubusercontent.com/8271749/57800607-28e4ef00-7728-11e9-8f45-3326c2173a58.png)

### Expected behavior
Passwords with "@" character should be accepted.

### Steps to reproduce the behavior
Use a password with "@" character.
Use a BaseUrl with "https"

**Comment by NGPixel** [comment]
Fixed by 4308152a0881e9ce841b99a253ccda0cb2f259d0

**Comment by mercplus** [comment]
Thanks for the merge. Is this fix not added to the prod build, version 2.5.170?

**Comment by rkblackfire** [comment]
Hello,

in my opinion the `encodeURI` should be an `encodeUriComponent`, because `encodeURI` escapes only characters which are forbidden in a URI but allows characters which are forbidden in a parameter thus producing invalid parameters.

For example if my password is `dough&icecream=benandjerrys`, the Git storage would try to login with `password=dough` which is wrong and a second parameter `icecream=benandjerrys` which would mean nothing to the server.

Maybe this bug exists in other places too?

see: [encodeURI on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)

**Comment by mazhewei** [comment]
The problem still exists.
If a password has an "@" character, encodeURI not convert "@" to "%40", should use ```encodeURIComponent``` instead of ```encodeURI ```
